### PR TITLE
Add zh_CN locale

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by MikkCZ** [comment]
Hi @yfdyh000. I am going to merge this and release a version with your contribution later today. Are you also interested in adding translation for https://addons.mozilla.org/firefox/addon/send-link-from-context-menu/ ?

**Comment by yfdyh000** [comment]
I'm not sure if I get what you mean. Are you saying the "It is a replacement for ..." need to translate?

**Comment by MikkCZ** [comment]
Yes. I does not *need* to translate, only if you want the add-on page to be translated.

**Comment by yfdyh000** [comment]
Okay, I misunderstood what you mean. I think it is not very useful and keep in English is acceptable.

**Pull request merged**
